linter:
  rules:
    - always_use_package_imports
    - avoid_empty_else
    - avoid_print
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - no_logic_in_create_state
    - prefer_void_to_null
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks
    - unsafe_html
    - use_key_in_widget_constructors
    - valid_regexps
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    # - always_specify_types
    - annotate_overrides
    # - avoid_annotating_with_dynamic
    - avoid_dynamic_calls
    - avoid_bool_literals_in_conditional_expressions
    # - avoid_catches_without_on_clauses
    - avoid_catching_errors
    # - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    # - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_multiple_declarations_per_line
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null
    - avoid_returning_null_for_void
    - avoid_returning_this
    # - avoid_setters_without_getters
    - avoid_single_cascade_in_expression_statements
    # - avoid_types_on_closure_parameters
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cascade_invocations
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - deprecated_consistency
    - directives_ordering
    - do_not_use_environment
    - empty_catches
    - empty_constructor_bodies
    - exhaustive_cases
    - file_names
    - implementation_imports
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    - lines_longer_than_80_chars
    - missing_whitespace_between_adjacent_strings
    - no_runtimeType_toString
    - non_constant_identifier_names
    - null_closures
    # - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    # - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_final_in_for_each
    # - prefer_final_locals
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - recursive_getters
    - sized_box_for_whitespace
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    # - unnecessary_getters_setters
    # - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_raw_strings
    - use_rethrow_when_possible
    # - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - void_checks
    - sort_pub_dependencies
    - require_trailing_commas
    # - implicit_call_tearoffs
    # - unnecessary_library_directive
    # - dangling_library_doc_comments
    # - library_annotations
    # - enable_null_safety
    - prefer_const_declarations
    - use_build_context_synchronously
    - library_private_types_in_public_api
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - package_names
    - prefer_for_elements_to_map_fromIterable
    - unnecessary_constructor_name
    - unnecessary_late
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_string_interpolations
    - unnecessary_this
analyzer:
  exclude: [lib/generated/**, lib/gen/**, lib/generated_plugin_registrant.dart]
  errors:
    always_use_package_imports: warning
    avoid_empty_else: warning
    avoid_print: warning
    avoid_returning_null_for_future: warning
    avoid_slow_async_io: warning
    avoid_type_to_string: warning
    avoid_types_as_parameter_names: warning
    avoid_web_libraries_in_flutter: warning
    cancel_subscriptions: warning
    close_sinks: warning
    comment_references: warning
    control_flow_in_finally: warning
    empty_statements: warning
    hash_and_equals: warning
    iterable_contains_unrelated_type: warning
    list_remove_unrelated_type: warning
    literal_only_boolean_expressions: warning
    no_adjacent_strings_in_list: warning
    no_duplicate_case_values: warning
    no_logic_in_create_state: warning
    prefer_void_to_null: warning
    test_types_in_equals: warning
    throw_in_finally: warning
    unnecessary_statements: warning
    unrelated_type_equality_checks: warning
    unsafe_html: warning
    use_key_in_widget_constructors: warning
    valid_regexps: warning
    always_declare_return_types: warning
    always_put_control_body_on_new_line: warning
    always_put_required_named_parameters_first: warning
    always_require_non_null_named_parameters: warning
    annotate_overrides: warning
    avoid_dynamic_calls: warning
    avoid_bool_literals_in_conditional_expressions: warning
    avoid_catching_errors: warning
    avoid_double_and_int_checks: warning
    avoid_equals_and_hash_code_on_mutable_classes: warning
    avoid_escaping_inner_quotes: warning
    avoid_init_to_null: warning
    avoid_multiple_declarations_per_line: warning
    avoid_null_checks_in_equality_operators: warning
    avoid_positional_boolean_parameters: warning
    avoid_private_typedef_functions: warning
    avoid_redundant_argument_values: warning
    avoid_renaming_method_parameters: warning
    avoid_return_types_on_setters: warning
    avoid_returning_null: warning
    avoid_returning_null_for_void: warning
    avoid_returning_this: warning
    avoid_single_cascade_in_expression_statements: warning
    avoid_unnecessary_containers: warning
    avoid_unused_constructor_parameters: warning
    avoid_void_async: warning
    await_only_futures: warning
    camel_case_extensions: warning
    camel_case_types: warning
    cascade_invocations: warning
    constant_identifier_names: warning
    curly_braces_in_flow_control_structures: warning
    deprecated_consistency: info
    directives_ordering: warning
    do_not_use_environment: warning
    empty_catches: warning
    empty_constructor_bodies: warning
    exhaustive_cases: warning
    file_names: warning
    implementation_imports: warning
    join_return_with_assignment: warning
    leading_newlines_in_multiline_strings: warning
    library_names: warning
    library_prefixes: warning
    lines_longer_than_80_chars: warning
    missing_whitespace_between_adjacent_strings: warning
    no_runtimeType_toString: warning
    non_constant_identifier_names: warning
    null_closures: warning
    only_throw_errors: warning
    overridden_fields: warning
    package_prefixed_library_names: warning
    parameter_assignments: warning
    prefer_adjacent_string_concatenation: warning
    prefer_asserts_in_initializer_lists: warning
    prefer_asserts_with_message: warning
    prefer_collection_literals: warning
    prefer_conditional_assignment: warning
    prefer_const_constructors: warning
    prefer_const_constructors_in_immutables: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_contains: warning
    prefer_equal_for_default_values: warning
    prefer_final_fields: warning
    prefer_final_in_for_each: warning
    prefer_foreach: warning
    prefer_function_declarations_over_variables: warning
    prefer_generic_function_type_aliases: warning
    prefer_if_null_operators: warning
    prefer_initializing_formals: warning
    prefer_inlined_adds: warning
    prefer_interpolation_to_compose_strings: warning
    prefer_is_empty: warning
    prefer_is_not_empty: warning
    prefer_is_not_operator: warning
    prefer_iterable_whereType: warning
    prefer_mixin: warning
    prefer_null_aware_operators: warning
    prefer_single_quotes: warning
    prefer_spread_collections: warning
    prefer_typing_uninitialized_variables: warning
    provide_deprecation_message: warning
    recursive_getters: warning
    sized_box_for_whitespace: warning
    slash_for_doc_comments: warning
    sort_child_properties_last: warning
    sort_constructors_first: warning
    sort_unnamed_constructors_first: warning
    type_init_formals: warning
    unawaited_futures: warning
    unnecessary_await_in_return: warning
    unnecessary_brace_in_string_interps: warning
    unnecessary_const: warning
    unnecessary_new: warning
    unnecessary_null_aware_assignments: warning
    unnecessary_null_in_if_null_operators: warning
    unnecessary_overrides: warning
    unnecessary_parenthesis: warning
    unnecessary_raw_strings: warning
    unnecessary_string_escapes: warning
    use_full_hex_values_for_flutter_colors: warning
    use_function_type_syntax_for_parameters: warning
    use_is_even_rather_than_modulo: warning
    use_named_constants: warning
    use_raw_strings: warning
    use_rethrow_when_possible: warning
    use_string_buffers: warning
    use_to_and_as_if_applicable: warning
    void_checks: warning
    sort_pub_dependencies: warning
    require_trailing_commas: warning
    prefer_const_declarations: warning
    use_build_context_synchronously: warning
    library_private_types_in_public_api: warning
    no_leading_underscores_for_library_prefixes: warning
    no_leading_underscores_for_local_identifiers: warning
    package_names: warning
    prefer_for_elements_to_map_fromIterable: warning
    unnecessary_constructor_name: warning
    unnecessary_late: warning
    unnecessary_nullable_for_final_variable_declarations: warning
    unnecessary_string_interpolations: warning
    unnecessary_this: warning